### ISSUE TITLE
cleverbot.py issue

### ISSUE THREAD

**Issue by Note2Self** [Lukkkim/BountyBot#6]
Hi there seems to be an issue with your cleverbot I get this error:

![image](https://user-images.githubusercontent.com/25305974/56096584-0cb02100-5ee2-11e9-879e-3d0c120c2aff.png)

**Comment by Lukkkim** [comment]
Hello, thank you for the post. I apologize for the long wait time in responding. This issue should now be resolved and cleverbot should be back up to normal. Please feel free to reach out if there are any other issues
